[package]
name = "wireworld"
version = "0.1.0"
authors = ["Vitor Fernandes <me@ghikio.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "^0.34.0"